apiVersion: v1
kind: Template
metadata:
  name: testapp-template

objects:
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: testapp-deployment
    spec:
      selector:
        matchLabels:
          app: testapp
      replicas: 1
      template:
        metadata:
          labels:
            app: testapp
        spec:
          containers:
            - name: testapp
              image: quay.io/cerveny/testapp:verzia-12
              imagePullPolicy: Always
              ports:
                - containerPort: 8080
      strategy:
        type: RollingUpdate
  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: testapp
      name: testapp-service
    spec:
      ports:
        - port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: testapp
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: testapp-route
      labels:
        app: testapp
    spec:
      to:
        kind: Service
        name: testapp-service
      port:
        targetPort: 8080