apiVersion: v1
kind: Template
metadata:
  name: testapp-template

objects:
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      name: testapp-is
      labels:
        app: testapp
    spec:
      lookupPolicy:
        local: false
      tags:
      - name: "latest"
        from:
          kind: DockerImage
          name: quay.io/cerveny/testapp:verzia-1
        referencePolicy:
          type: Source

  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      name: testapp-deployment
    spec:
      selector:
        matchLabels:
          app: testapp
      replicas: 1
      template:
        metadata:
          labels:
            app: testapp
        spec:
          containers:
            - name: testapp
              image: testapp-is
              imagePullPolicy: Always
              ports:
                - containerPort: 8080
      triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true       # Set automatic=true to trigger a redeployment on image change
          containerNames:
            - testapp
          from:
            kind: ImageStreamTag
            namespace: testapp-imagestream
            name: 'testapp-is:latest'

  - kind: Service
    apiVersion: v1
    metadata:
      name: testapp-service
      labels:
        app: testapp
    spec:
      ports:
        - port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: testapp

  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: testapp-route
      labels:
        app: testapp
    spec:
      to:
        kind: Service
        name: testapp-service
      port:
        targetPort: 8080