apiVersion: v1
kind: Template
metadata:
  name: build-config 

objects:
  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      name: testapp-quay
    spec:
      nodeSelector: {}
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            namespace: openshift
            name: 'httpd:2.4-el7'
      source:
        type: Git
        git:
          uri: 'https://github.com/martinmlkvy/testapp.git'
          ref: master
      output:
        to:
          kind: DockerImage
          name: 'quay.io/cerveny/testapp:verzia-${TAG}'
        pushSecret:
          name: quay-credentials

parameters:
  - name: TAG
    description: "Tag for image pushed to quay"
    required: true
