kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: test-dockerfile
spec:
  nodeSelector: {}
  strategy:
    type: Docker
  source:
    type: Git
    git:
      uri: 'https://github.com/martinmlkvy/testapp.git'
      ref: dev
  output:
    to:
      kind: DockerImage
      name: quay.io/cerveny/testapp
    pushSecret:
      name: quay-credentials