//pipeline na deploy do DEV
pipeline{
    agent any

    environment { 
        NAMESPACE = "testapp-prod"
    }

    stages{
        stage("Test"){
            steps{
                echo "testujem aplikaciu"
            }           
        }
      
        stage("Deploy to prod"){
            steps{
                sh '''
                    oc set image deployment testapp-deployment \
                    testapp=quay.io/cerveny/testapp:${appVersion} \
                    -n ${NAMESPACE} --record                
                '''                
            }
        }
    }
}