//pipeline na deploy do DEV
pipeline{
    agent any

    environment { 
        NAMESPACE = "testapp-prod"
    }

    stages{
        stage("Test"){
            steps{
                echo "testujem aplikaciu"
            }           
        }
      
        stage("Deploy to prod"){
            script {
                // Variables for input
                def inputVersion

                // Get the input
                def userInput = input(
                        id: 'userInput', message: 'Enter version to deploy into production',
                        parameters: [
                            string(defaultValue: 'None',
                                    description: 'Version',
                                    name: 'version'),
                        ])

                // Save to variables. Default to empty string if not found.
                inputVersion = userInput.version?:''

                // Echo to console
                echo('Into production will be deployed version ${inputVersion}')

                sh '''
                    oc set image deployment testapp-deployment \
                    testapp=quay.io/cerveny/testapp:${inputVersion} \
                    -n ${NAMESPACE} --record                
                '''
            }
        }
    }
}